simple_html_example = %{}

{ simple_html_example: %{},
  action: {
    html: %{},
    regexp: %{},
    string: %{}},
  after: {
    element: %{},
    html: %{}},
  alt: {
    html: %{},
    regexp: %{},
    string: %{}},
  class: {
    html: %{},
    regexp: %{},
    string: %{}},
  css: {
    html: %{},
    string: %{}},
  for: {
    html: %{},
    regexp: %{},
    string: %{}},
  href: {
    html: %{},
    regexp: %{},
    string: %{}},
  html: {
    html: %{},
    regexp: %{},
    string: %{}},
  id: {
    html: %{},
    regexp: %{},
    string: %{}},
  index: {
    html: %{},
    implicit: %{},
    integer: %{}},
  method: {
    html: %{},
    regexp: %{},
    string: %{}},
  name: {
    html: %{},
    regexp: %{},
    string: %{}},
  src: {
    html: %{},
    regexp: %{},
    string: %{}},
  text: {
    html: %{},
    regexp: %{},
    string: %{}},
  title: {
    html:   %{},
    regexp: %{},
    string: %{}},
  url: {
    html:   %{},
    regexp: %{},
    string: %{}},
  value: {
    html: %{},
    regexp: %{},
    string: %{}},
  xpath:{
    element_by_xpath: %{},
    html: %{},
    xpath: %{}},
  multiple_attributes: {
    hash: %{},
    html: %{}},
  collection: {
    example: %{},
    html: %{}}}
